"""Assert the business story against actual DuckDB state; preserve generated evidence."""

import argparse
import json
from pathlib import Path
from uuid import uuid4

from marketing_reliability.warehouse import GateError, Warehouse

ROOT = Path(__file__).resolve().parents[1]


def save(path, value):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(value, indent=2, ensure_ascii=False, sort_keys=True) + "\n",
        encoding="utf-8",
        newline="\n",
    )


def execute(state, output):
    if (state / "warehouse.duckdb").exists():
        raise ValueError("demo requires a new state directory")
    phases = []
    with Warehouse(state) as w:
        for number in range(1, 5):
            path = next(ROOT.joinpath("fixtures").glob(f"{number:02d}-*.json"))
            assert w.ingest(path.read_bytes())["status"] == "accepted"
        baseline = w.plan("2026-09-04")
        w.build(baseline)
        w.publish(baseline)
        before = w.table()
        assert sum(r[3] for r in before) == 36000
        assert sum(r[6] for r in before) == 4
        assert sum(r[7] for r in before) == 150000
        phases.append({"phase": "baseline", "run": w.run(baseline), "table": before})
        replay = w.ingest(ROOT.joinpath("fixtures/03-web.json").read_bytes())
        assert replay["replayed"] and w.table() == before
        stale = w.plan("2026-09-06")
        stale_result = w.build(stale)
        assert len(stale_result["evidence"]["blockers"]) == 4
        try:
            w.publish(stale)
        except GateError:
            pass
        else:
            raise AssertionError("stale source coverage published")
        phases.append({"phase": "stale_feed_blocked", "run": stale_result})
        rejected = w.ingest(ROOT.joinpath("fixtures/10-unsupported-schema.json").read_bytes())
        assert rejected["status"] == "rejected"
        for number in range(5, 8):
            path = next(ROOT.joinpath("fixtures").glob(f"{number:02d}-*.json"))
            assert w.ingest(path.read_bytes())["status"] == "accepted"
        incomplete = w.plan("2026-09-06")
        incomplete_result = w.build(incomplete)
        assert len(incomplete_result["evidence"]["unresolved"]) == 2
        try:
            w.publish(incomplete)
        except GateError:
            pass
        else:
            raise AssertionError("missing campaign reference published")
        assert w.table() == before
        phases.append({"phase": "reference_gap_blocked", "run": incomplete_result})
        for number in (8, 9):
            path = next(ROOT.joinpath("fixtures").glob(f"{number:02d}-*.json"))
            w.ingest(path.read_bytes())
        corrected = w.plan("2026-09-06")
        w.build(corrected)
        w.publish(corrected)
        final = w.table()
        assert sum(r[3] for r in final) == 41000
        assert sum(r[6] for r in final) == 6
        assert sum(r[7] for r in final) == 115000
        assert w.table(baseline) == before
        phases.append({"phase": "corrected", "run": w.run(corrected), "table": final})
        backfill = w.plan("2026-09-06", dates=["2026-09-01"])
        w.build(backfill)
        w.publish(backfill)
        assert w.table() == final
        phases.append({"phase": "bounded_backfill", "run": w.run(backfill)})
        full = w.plan("2026-09-06", full=True)
        w.build(full)
        w.publish(full)
        assert w.table() == final
        phases.append({"phase": "full_rebuild", "run": w.run(full)})
        report = w.reconcile()
        assert report["row_dispositions"]["quarantined"] == 2
        assert not report["dirty_dates"]
        save(output / "reconciliation.json", report)
        save(
            output / "lineage.json",
            {
                "run_id": full,
                "columns": [
                    "source",
                    "id",
                    "revision",
                    "op",
                    "day",
                    "campaign_id",
                    "delivery_sha256",
                    "line",
                ],
                "rows": w.lineage(full),
            },
        )
        save(
            output / "pipeline-runs.json",
            {"phases": phases, "replay_receipt": replay, "schema_rejection": rejected},
        )
        text = f"""# Executed marketing data reliability proof

All input records and business outcomes are synthetic. Generated by `scripts/demo.py`.

| Published measure | Baseline | After corrections |
|---|---:|---:|
| Spend | $360 | $410 |
| Observed web conversions | 4 | 6 |
| Closed-won CRM revenue | $1,500 | $1,150 |

These measures are separate source facts joined by supplied campaign ID, not causal attribution or ROAS.

The spend change is +$10 for a corrected source record and +$40 for a late partner campaign. Web conversions gain a late event, a repaired quarantined row and a partner event, and lose one deleted event (+2 net). One conversion moves between dates without changing the total. CRM revenue changes by -$50 on a corrected opportunity and -$300 on a deletion; the corrected opportunity also moves from September 2 to 3.

- A repeated file returned its original receipt without adding versions.
- Missing freshness evidence blocked a candidate on all four feeds.
- Unsupported paid-media schema version 3 was retained and rejected as a whole delivery.
- Two unresolved campaign references blocked publication until campaign data arrived.
- A lower revision arrived after revision 3 and did not overwrite it.
- A one-day rebuild and full rebuild exactly matched the corrected publication.
- The original publication remained queryable after corrections.

Accepted delivery rows: **{report["accepted_delivery_rows"]}**. Outcomes: **{json.dumps(report["row_dispositions"], sort_keys=True)}**.
Admitted versions: **{report["admitted_versions"]}** = {report["superseded_versions"]} superseded + {report["current_tombstones"]} current tombstones + {report["current_live_records"]} current live records.

Quarantined raw rows remain in the ledger even after an upstream repair. A rejected delivery is separate from accepted-delivery row accounting. Coverage is a supplied source assertion, not proof of upstream completeness. Published measures exclude quarantined rows and must be read with this qualification.

See [row reconciliation](reconciliation.json), [publication gates and rebuilds](pipeline-runs.json), [source lineage](lineage.json), and [process crash recovery](recovery.json). Verification produces the crash evidence separately by terminating real subprocesses.
"""
        output.joinpath("report.md").write_text(text, encoding="utf-8", newline="\n")
    return report


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--state", type=Path, default=ROOT / "work" / f"demo-{uuid4().hex}")
    parser.add_argument("--output", type=Path, default=ROOT / "docs/evidence")
    args = parser.parse_args()
    result = execute(args.state, args.output)
    print(
        json.dumps(
            {
                "state": str(args.state),
                "output": str(args.output),
                "active_run": result["active_run"],
            }
        )
    )
